/*
 * This file was automatically generated by EvoSuite
 * Mon Sep 23 17:57:13 GMT 2019
 */

package org.example.helloWorld;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.example.helloWorld.Program;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Program_ESTest extends Program_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      boolean boolean0 = Program.isEvenNumber(1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = Program.getAccountYear();
      assertEquals(2013, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      System.setCurrentTimeMillis((-4004L));
      int int0 = Program.getAccountYear();
      assertEquals(1969, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      boolean boolean0 = Program.isEvenNumber(2014);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      boolean boolean0 = Program.isEvenNumber((-3273));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Program program0 = new Program();
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      int int0 = Program.getYear();
      assertEquals(2014, int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Program.main(stringArray0);
      assertEquals(0, stringArray0.length);
  }
}
